export const COUNTRY_OPTIONS = [
  { code: "AF", label: "🇦🇫 Afghanistan (+93)" },
  { code: "AL", label: "🇦🇱 Albania (+355)" },
  { code: "DZ", label: "🇩🇿 Algeria (+213)" },
  { code: "AD", label: "🇦🇩 Andorra (+376)" },
  { code: "AO", label: "🇦🇴 Angola (+244)" },
  { code: "AR", label: "🇦🇷 Argentina (+54)" },
  { code: "AM", label: "🇦🇲 Armenia (+374)" },
  { code: "AU", label: "🇦🇺 Australia (+61)" },
  { code: "AT", label: "🇦🇹 Austria (+43)" },
  { code: "AZ", label: "🇦🇿 Azerbaijan (+994)" },
  { code: "BH", label: "🇧🇭 Bahrain (+973)" },
  { code: "BD", label: "🇧🇩 Bangladesh (+880)" },
  { code: "BY", label: "🇧🇾 Belarus (+375)" },
  { code: "BE", label: "🇧🇪 Belgium (+32)" },
  { code: "BZ", label: "🇧🇿 Belize (+501)" },
  { code: "BJ", label: "🇧🇯 Benin (+229)" },
  { code: "BT", label: "🇧🇹 Bhutan (+975)" },
  { code: "BO", label: "🇧🇴 Bolivia (+591)" },
  { code: "BA", label: "🇧🇦 Bosnia & Herzegovina (+387)" },
  { code: "BW", label: "🇧🇼 Botswana (+267)" },
  { code: "BR", label: "🇧🇷 Brazil (+55)" },
  { code: "BG", label: "🇧🇬 Bulgaria (+359)" },
  { code: "KH", label: "🇰🇭 Cambodia (+855)" },
  { code: "CM", label: "🇨🇲 Cameroon (+237)" },
  { code: "CA", label: "🇨🇦 Canada (+1)" },
  { code: "CL", label: "🇨🇱 Chile (+56)" },
  { code: "CN", label: "🇨🇳 China (+86)" },
  { code: "CO", label: "🇨🇴 Colombia (+57)" },
  { code: "CR", label: "🇨🇷 Costa Rica (+506)" },
  { code: "HR", label: "🇭🇷 Croatia (+385)" },
  { code: "CU", label: "🇨🇺 Cuba (+53)" },
  { code: "CY", label: "🇨🇾 Cyprus (+357)" },
  { code: "CZ", label: "🇨🇿 Czech Republic (+420)" },
  { code: "DK", label: "🇩🇰 Denmark (+45)" },
  { code: "DO", label: "🇩🇴 Dominican Republic (+1)" },
  { code: "EC", label: "🇪🇨 Ecuador (+593)" },
  { code: "EG", label: "🇪🇬 Egypt (+20)" },
  { code: "EE", label: "🇪🇪 Estonia (+372)" },
  { code: "ET", label: "🇪🇹 Ethiopia (+251)" },
  { code: "FI", label: "🇫🇮 Finland (+358)" },
  { code: "FR", label: "🇫🇷 France (+33)" },
  { code: "GE", label: "🇬🇪 Georgia (+995)" },
  { code: "DE", label: "🇩🇪 Germany (+49)" },
  { code: "GH", label: "🇬🇭 Ghana (+233)" },
  { code: "GR", label: "🇬🇷 Greece (+30)" },
  { code: "GT", label: "🇬🇹 Guatemala (+502)" },
  { code: "HN", label: "🇭🇳 Honduras (+504)" },
  { code: "HK", label: "🇭🇰 Hong Kong (+852)" },
  { code: "HU", label: "🇭🇺 Hungary (+36)" },
  { code: "IS", label: "🇮🇸 Iceland (+354)" },
  { code: "IN", label: "🇮🇳 India (+91)" },
  { code: "ID", label: "🇮🇩 Indonesia (+62)" },
  { code: "IR", label: "🇮🇷 Iran (+98)" },
  { code: "IQ", label: "🇮🇶 Iraq (+964)" },
  { code: "IE", label: "🇮🇪 Ireland (+353)" },
  { code: "IL", label: "🇮🇱 Israel (+972)" },
  { code: "IT", label: "🇮🇹 Italy (+39)" },
  { code: "JM", label: "🇯🇲 Jamaica (+1)" },
  { code: "JP", label: "🇯🇵 Japan (+81)" },
  { code: "JO", label: "🇯🇴 Jordan (+962)" },
  { code: "KZ", label: "🇰🇿 Kazakhstan (+7)" },
  { code: "KE", label: "🇰🇪 Kenya (+254)" },
  { code: "KR", label: "🇰🇷 South Korea (+82)" },
  { code: "KW", label: "🇰🇼 Kuwait (+965)" },
  { code: "LA", label: "🇱🇦 Laos (+856)" },
  { code: "LV", label: "🇱🇻 Latvia (+371)" },
  { code: "LB", label: "🇱🇧 Lebanon (+961)" },
  { code: "LY", label: "🇱🇾 Libya (+218)" },
  { code: "LI", label: "🇱🇮 Liechtenstein (+423)" },
  { code: "LT", label: "🇱🇹 Lithuania (+370)" },
  { code: "LU", label: "🇱🇺 Luxembourg (+352)" },
  { code: "MO", label: "🇲🇴 Macau (+853)" },
  { code: "MY", label: "🇲🇾 Malaysia (+60)" },
  { code: "MT", label: "🇲🇹 Malta (+356)" },
  { code: "MU", label: "🇲🇺 Mauritius (+230)" },
  { code: "MX", label: "🇲🇽 Mexico (+52)" },
  { code: "MD", label: "🇲🇩 Moldova (+373)" },
  { code: "MC", label: "🇲🇨 Monaco (+377)" },
  { code: "MN", label: "🇲🇳 Mongolia (+976)" },
  { code: "ME", label: "🇲🇪 Montenegro (+382)" },
  { code: "MA", label: "🇲🇦 Morocco (+212)" },
  { code: "MZ", label: "🇲🇿 Mozambique (+258)" },
  { code: "MM", label: "🇲🇲 Myanmar (+95)" },
  { code: "NP", label: "🇳🇵 Nepal (+977)" },
  { code: "NL", label: "🇳🇱 Netherlands (+31)" },
  { code: "NZ", label: "🇳🇿 New Zealand (+64)" },
  { code: "NG", label: "🇳🇬 Nigeria (+234)" },
  { code: "NO", label: "🇳🇴 Norway (+47)" },
  { code: "OM", label: "🇴🇲 Oman (+968)" },
  { code: "PK", label: "🇵🇰 Pakistan (+92)" },
  { code: "PA", label: "🇵🇦 Panama (+507)" },
  { code: "PY", label: "🇵🇾 Paraguay (+595)" },
  { code: "PE", label: "🇵🇪 Peru (+51)" },
  { code: "PH", label: "🇵🇭 Philippines (+63)" },
  { code: "PL", label: "🇵🇱 Poland (+48)" },
  { code: "PT", label: "🇵🇹 Portugal (+351)" },
  { code: "QA", label: "🇶🇦 Qatar (+974)" },
  { code: "RO", label: "🇷🇴 Romania (+40)" },
  { code: "RU", label: "🇷🇺 Russia (+7)" },
  { code: "SA", label: "🇸🇦 Saudi Arabia (+966)" },
  { code: "RS", label: "🇷🇸 Serbia (+381)" },
  { code: "SG", label: "🇸🇬 Singapore (+65)" },
  { code: "SK", label: "🇸🇰 Slovakia (+421)" },
  { code: "SI", label: "🇸🇮 Slovenia (+386)" },
  { code: "ZA", label: "🇿🇦 South Africa (+27)" },
  { code: "ES", label: "🇪🇸 Spain (+34)" },
  { code: "LK", label: "🇱🇰 Sri Lanka (+94)" },
  { code: "SE", label: "🇸🇪 Sweden (+46)" },
  { code: "CH", label: "🇨🇭 Switzerland (+41)" },
  { code: "TW", label: "🇹🇼 Taiwan (+886)" },
  { code: "TH", label: "🇹🇭 Thailand (+66)" },
  { code: "TR", label: "🇹🇷 Turkey (+90)" },
  { code: "UA", label: "🇺🇦 Ukraine (+380)" },
  { code: "AE", label: "🇦🇪 United Arab Emirates (+971)" },
  { code: "GB", label: "🇬🇧 United Kingdom (+44)" },
  { code: "US", label: "🇺🇸 United States (+1)" },
  { code: "UY", label: "🇺🇾 Uruguay (+598)" },
  { code: "UZ", label: "🇺🇿 Uzbekistan (+998)" },
  { code: "VE", label: "🇻🇪 Venezuela (+58)" },
  { code: "VN", label: "🇻🇳 Vietnam (+84)" },
  { code: "YE", label: "🇾🇪 Yemen (+967)" },
  { code: "ZM", label: "🇿🇲 Zambia (+260)" },
  { code: "ZW", label: "🇿w Zimbabwe (+263)" },
];